# Generated by Django 4.0 on 2021-12-19 17:33

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('forum_conversation', '0011_remove_post_poster_ip'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostsSearchIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('subject', models.CharField(max_length=255)),
                ('search_vector_all', django.contrib.postgres.search.SearchVectorField(null=True)),
                ('search_vector_subject', django.contrib.postgres.search.SearchVectorField(null=True)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum_conversation.Topic')),
            ],
            options={
                'verbose_name': 'post_search_index'
            },
        ),
        migrations.AddIndex(
            model_name='postssearchindex',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector_all'], name='search_post_search__6dc42b_gin'),
        ),
        migrations.AddIndex(
            model_name='postssearchindex',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector_subject'], name='search_post_search__e2c975_gin'),
        ),
    ]
