# Generated by Django 2.2.9 on 2020-01-30 19:40

from django.db import migrations
from machina_search import settings


class Migration(migrations.Migration):

    dependencies = [
        ('forum_conversation', '0011_remove_post_poster_ip'),
    ]

    if settings.SEARCH_ENGINE == 'postgres':
        operations = [
            migrations.RunSQL(
                    sql='''
                    ALTER TABLE forum_conversation_post
                    ADD COLUMN search_vector_all tsvector;

                    ALTER TABLE forum_conversation_post
                    ADD COLUMN search_vector_subject tsvector;

                    CREATE INDEX post_search_idx
                    ON forum_conversation_post
                    USING GIN (search_vector_all);

                    CREATE INDEX post_subject_search_idx
                    ON forum_conversation_post
                    USING GIN (search_vector_subject);

                    CREATE TRIGGER post_update_trigger_all
                    BEFORE INSERT OR UPDATE OF subject, content, search_vector_all
                    ON forum_conversation_post
                    FOR EACH ROW EXECUTE PROCEDURE
                    tsvector_update_trigger(
                      search_vector_all, 'pg_catalog.{0}', subject, content);

                    CREATE TRIGGER post_update_trigger_subject
                    BEFORE INSERT OR UPDATE OF subject, search_vector_subject
                    ON forum_conversation_post
                    FOR EACH ROW EXECUTE PROCEDURE
                    tsvector_update_trigger(
                      search_vector_subject, 'pg_catalog.{0}', subject);

                    UPDATE forum_conversation_post
                    SET search_vector_all = NULL, search_vector_subject = NULL;
                    '''.format(settings.SEARCH_LANGUAGE),

                    reverse_sql='''
                    ALTER TABLE forum_conversation_post
                        DROP COLUMN IF EXISTS search_vector_all,
                        DROP COLUMN IF EXISTS search_vector_subject;
                    DROP INDEX IF EXISTS post_search_idx;
                    DROP INDEX IF EXISTS post_subject_search_idx;
                    DROP TRIGGER IF EXISTS post_update_trigger_all, post_update_trigger_subject
                    ON forum_conversation_post;
                    '''),
        ]
    else:
        operations = []
